### ISSUE TITLE
LiSA implementation of mrouter_set|reset|get

### ISSUE THREAD

**Issue by claudiughioc** [lisa-project/lisa-user#12]
We need to have an implementation of mrouter_set|reset|get using the LiSA kernel module.

**Comment by mihaelamartinas** [comment]
Commit: e0feba8674db4101a0e146cc18fd1442f881b5db

I modified the signature of mrouter_set to receive an other parameter which indicates if mrouter should be set or reset. In this way mrouter_reset isn't needed anymore.
