### ISSUE TITLE
vif_add|del, if_set_port_vlan, get_vlan_interfaces

### ISSUE THREAD

**Issue by acrish** [lisa-project/lisa-user#18]

**Comment by mihaelamartinas** [comment]
Commit: 6ed6813e9554c67b5967357e1822ddca400313b8
Commit: ab7f0fe14b316c60b4723ffec469d62396d54a44
I accidently pushed it under the name Lisa Virtual Machine

I let the task open because vif_del still doesn't work.

**Comment by mihaelamartinas** [comment]
What caused the problem was a deadlock from kernel, which was fixed in this commit: db70a22a60474039a1863dc3e2839b78eb2c1a01
