### ISSUE TITLE
CLI constants from kernel space in user space

### ISSUE THREAD

**Issue by acrish** [lisa-project/lisa-user#42]
- constants like: SWCFG_SETACCESS, SWCFG_SETTRUNK, SW_IF_VIF | ROUTED etc.
  What happens to these constants? A solution would be to add a macro in sw_api which defines them if they are not defined.

**Comment by claudiughioc** [comment]
Already done that. Check sw_api.h and use those.

**Comment by claudiughioc** [comment]
Also they are mapped over the kernel constants so they should work.
