### ISSUE TITLE
API redesign of function "get_vlan_interfaces" 

### ISSUE THREAD

**Issue by victorduta** [lisa-project/lisa-user#49]
The function currently takes a pointer to a preallocated block of memory and fills it with interface indexes . Yet there might be a chance that the prealocated block isn't big enough to store all interface indexes . This function should take a int*\* and backend implementations should realloc the buffer size if needed . This function must also receive in "no_ifs" the number of interfaces for wich space if preallocated. Waiting on your feedback on this issue .

**Comment by rrendec** [comment]
Isn't it easier to just allocate the buffer from the backend to the size that is required to store all indexes? Depending on the implementation, the backend may know in advance how many interfaces it needs to return. In this case, it doesn't make much sense to preallocate and then reallocate the buffer.

**Comment by victorduta** [comment]
Yes that is the easiest way to do it but you have to iterate to find out
the number of interfaces and then iterate again to add them in the buffer .
Though in Bridge and 8021q we could keep an aditional index in the
vlan_data structure so we could know in advance the number of interfaces in
the vlan. Anyway this aproach is better then the one with reallocation :).
