### ISSUE TITLE
Remove the vlan description from the lisa kernel module

### ISSUE THREAD

**Issue by acrish** [lisa-project/lisa-user#5]

**Comment by claudiughioc** [comment]
I removed the kernel handling of iotcl command SWCFG_RENAMEVLAN.

**Comment by claudiughioc** [comment]
When a vlan is added (command SWCFG_ADDVLAN)  the module calls sw_vdb_add_vlan which initially received also the vlan description. Now this parameter will not be added. If we remove the vlan description from kernel space there are some changes that must be done in user space.
- on switch_init (kernel) 5 vlans were added in the VDB. Their description must be added now from user space:
  - sw_vdb_add_vlan(sw, 1, "default");
  - sw_vdb_add_vlan(sw, 1002, "fddi-default");
  - sw_vdb_add_vlan(sw, 1003, "trcrf-default");
  - sw_vdb_add_vlan(sw, 1004, "fddinet-default");
  - sw_vdb_add_vlan(sw, 1005, "trbrf-default");
- also on SWCFG_ADDVIF and SWCFG_SETPORTVLAN if the given vlan doesn't exist it will be added with a default description: sprintf(buf, "VLAN%04d", vlan). This must be handled from userspace too.

**Comment by claudiughioc** [comment]
I have completely removed the VLAN description. This was printed using procfs along with other VLAN details. I did not removed the procfs feature, I have only removed the description from being printed. Maybe be will use it again sometimes, or port it to sysfs.
