### ISSUE TITLE
[CLI] Trunk allow vlan

### ISSUE THREAD

**Issue by acrish** [lisa-project/lisa-user#51]
```
config> int netdev dummy1
config-if> switchport trunk allow vlan 2
> show running-config int netdev dummy1
```

The sequence of code prints "...switchport trunk allow vlan 1,3-...".

Shouldn't it print "...switchport trunk allow vlan 2" ?

**Comment by rrendec** [comment]
I believe the bitmap logic is reversed (negated) at some point. "1,3-..." is exactly the opposite, meaning "all vlans, except 2".

I remember we discussed to always keep the bitmaps in positive logic across all the userspace part, for simplicity. Maybe you forgot to negate the bitmap before passing it to the kernel for "switchport trunk allow vlan"? The kernel module expects to receive the bitmap in reverse logic.

**Comment by claudiughioc** [comment]
Hey,

I has looking over the "GETVDB" code in lisa.ko. Actually it returns a
bitmap with forbidden VLANs, and the LiSA switch API function "get_vdb"
just forwards the bitmap as is. The middleware function should negate the
bitmap in positive logic and this should be solved.

**Comment by acrish** [comment]
- actually in LiSA middleware all vlan bitmaps were missed up (setting, adding, retrieving), because they were passed to kernel in allowed format and were retrieved as allowed even though the kernel module considered the bitmap as forbidden vlans
- here it is the fix: https://github.com/lisa-project/lisa-user/commit/3b708507e43ea055cfc9764e70fd0b4abf7b9c39
