### ISSUE TITLE
Modification in  LISA implementation of "get_vlan_intefaces".

### ISSUE THREAD

**Issue by victorduta** [lisa-project/lisa-user#59]

**Comment by victorduta** [comment]
Commit https://github.com/lisa-project/lisa-user/commit/12cb155f362ce299c2c2ac976c9086f9a550d89a

**Comment by acrish** [comment]
There are compilation warnings after this commit because the API has been changed, but the the calls to get_vlan_interfaces has not been updated.

**Comment by victorduta** [comment]
i've updated them , but i forgot to synchronize my VB time with my host and
the commit is registered to be done 25 days ago . I've synchronized my
clock and mistakes like this won't happen again

**Comment by acrish** [comment]
- update and cleanup after modifications in sw_api:
  https://github.com/lisa-project/lisa-user/commit/ed38d6225e135cc6fc22afa1c2960f5cdbc8b33a
  https://github.com/lisa-project/lisa-user/commit/bca1f2cb812d4806057543a064f22c6abb92355a
