### ISSUE TITLE
Finalize switch API

### ISSUE THREAD

**Issue by acrish** [lisa-project/lisa-user#8]
- based on the observations from https://github.com/lisa-project/lisa-user/commit/115ab601f582f9c931cc72009203ae0f58fad2eb#commitcomment-2808347

**Comment by acrish** [comment]
Almost done, needs a review and maybe comments if considered necessary.

Please see https://github.com/lisa-project/lisa-user/commit/fc097a32599cf3f6ee84e82a1461ae0ae423be1f as I didn't notice the virtual machine I was working on did not have the date configured properly.

**Comment by claudiughioc** [comment]
I think it looks good. Any eventual changes will be added when needed.
