### ISSUE TITLE
Check "save running config" mechanism

### ISSUE THREAD

**Issue by claudiughioc** [lisa-project/lisa-user#9]
There is a "save runnig config" mechanism which saves the switch configuration in "/etc/lisa". This functionality must be checked.
Also we have to make sure the file is saved even if the directory doesn't exist.

**Comment by acrish** [comment]
- it may help to start from include/shared.h macros and cli/swcfgload.c and cli/cfgbuild/cfgbuild.c

**Comment by rrendec** [comment]
At least on my home server it works ;) But I'm quite sure it doesn't create /etc/lisa if it doesn't exist. It's arguable if this is the responsibility of the linux distribution packaging, the cli (when you issue "write mem"), or both.

**Comment by gear6468** [comment]
i think the distro package should create /etc/lisa in the post-install script.
the cli should give a descriptive error on issuing 'write mem' if the directory doesn't exist, or if it cannot create/write the config file.

**Comment by rrendec** [comment]
I agree. However, /etc/lisa is created by the top-level Makefile, in the "install" rule: `mkdir -p $(ROOT)/etc/lisa/tags`
The .spec file only packages the directory, it doesn't explicitly create it in the post-install script.
